### ISSUE TITLE
Got "application error" on Heroku

### ISSUE THREAD

**Issue by MathRobin** [salesforce/get-you-a-license#1]
Hi, thanks for this repo, sorry but not really good at understanding java error message :

```
Starting process with command `target/universal/stage/bin/get-you-a-license -Dhttp.port=8498`
2018-01-29T13:58:24.054782+00:00 app[web.1]: Create a Procfile to customize the command used to run this process: https://devcenter.heroku.com/articles/procfile
2018-01-29T13:58:24.078592+00:00 app[web.1]: Setting JAVA_TOOL_OPTIONS defaults based on dyno size. Custom settings will override them.
2018-01-29T13:58:24.278133+00:00 app[web.1]: Picked up JAVA_TOOL_OPTIONS: -Xmx300m -Xss512k -Dfile.encoding=UTF-8 
2018-01-29T13:58:27.768621+00:00 app[web.1]: Oops, cannot start the server.
2018-01-29T13:58:27.770829+00:00 app[web.1]: Configuration error: Configuration error[
2018-01-29T13:58:27.770833+00:00 app[web.1]: The application secret has not been set, and we are in prod mode. Your application is not secure.
2018-01-29T13:58:27.770835+00:00 app[web.1]: To set the application secret, please read http://playframework.com/documentation/latest/ApplicationSecret
2018-01-29T13:58:27.770837+00:00 app[web.1]:           ]
2018-01-29T13:58:27.770840+00:00 app[web.1]: 	at play.api.Configuration$.configError(Configuration.scala:156)
2018-01-29T13:58:27.770843+00:00 app[web.1]: 	at play.api.Configuration.reportError(Configuration.scala:990)
2018-01-29T13:58:27.770846+00:00 app[web.1]: 	at play.api.http.HttpConfiguration$.getSecretConfiguration(HttpConfiguration.scala:253)
2018-01-29T13:58:27.770848+00:00 app[web.1]: 	at play.api.http.HttpConfiguration$.fromConfiguration(HttpConfiguration.scala:238)
2018-01-29T13:58:27.770849+00:00 app[web.1]: 	at play.api.BuiltInComponents.httpConfiguration(Application.scala:284)
2018-01-29T13:58:27.770851+00:00 app[web.1]: 	at play.api.BuiltInComponents.httpConfiguration$(Application.scala:284)
2018-01-29T13:58:27.770853+00:00 app[web.1]: 	at play.api.BuiltInComponentsFromContext.httpConfiguration$lzycompute(ApplicationLoader.scala:122)
2018-01-29T13:58:27.770854+00:00 app[web.1]: 	at play.api.BuiltInComponentsFromContext.httpConfiguration(ApplicationLoader.scala:122)
2018-01-29T13:58:27.770856+00:00 app[web.1]: 	at play.api.BuiltInComponents.cookieSigner(Application.scala:330)
2018-01-29T13:58:27.770879+00:00 app[web.1]: 	at play.api.BuiltInComponents.cookieSigner$(Application.scala:330)
2018-01-29T13:58:27.771004+00:00 app[web.1]: 	at play.api.BuiltInComponentsFromContext.cookieSigner$lzycompute(ApplicationLoader.scala:122)
2018-01-29T13:58:27.771080+00:00 app[web.1]: 	at play.api.BuiltInComponentsFromContext.cookieSigner(ApplicationLoader.scala:122)
2018-01-29T13:58:27.771166+00:00 app[web.1]: 	at play.api.BuiltInComponents.injector(Application.scala:271)
2018-01-29T13:58:27.771250+00:00 app[web.1]: 	at play.api.BuiltInComponents.injector$(Application.scala:269)
2018-01-29T13:58:27.771388+00:00 app[web.1]: 	at play.api.BuiltInComponentsFromContext.injector$lzycompute(ApplicationLoader.scala:122)
2018-01-29T13:58:27.771407+00:00 app[web.1]: 	at play.api.BuiltInComponentsFromContext.injector(ApplicationLoader.scala:122)
2018-01-29T13:58:27.771413+00:00 app[web.1]: 	at play.api.BuiltInComponents.application(Application.scala:323)
2018-01-29T13:58:27.771451+00:00 app[web.1]: 	at play.api.BuiltInComponents.application$(Application.scala:323)
2018-01-29T13:58:27.771522+00:00 app[web.1]: 	at play.api.BuiltInComponentsFromContext.application$lzycompute(ApplicationLoader.scala:122)
2018-01-29T13:58:27.771604+00:00 app[web.1]: 	at play.api.BuiltInComponentsFromContext.application(ApplicationLoader.scala:122)
2018-01-29T13:58:27.771659+00:00 app[web.1]: 	at MyApplicationLoader.load(MyApplicationLoader.scala:47)
2018-01-29T13:58:27.771728+00:00 app[web.1]: 	at play.core.server.ProdServerStart$.start(ProdServerStart.scala:51)
2018-01-29T13:58:27.771782+00:00 app[web.1]: 	at play.core.server.ProdServerStart$.main(ProdServerStart.scala:25)
2018-01-29T13:58:27.771849+00:00 app[web.1]: 	at play.core.server.ProdServerStart.main(ProdServerStart.scala)
2018-01-29T13:58:27.856083+00:00 heroku[web.1]: Process exited with status 255
2018-01-29T13:58:27.873023+00:00 heroku[web.1]: State changed from starting to crashed
```

Env vars (GITHUB_OAUTH_CLIENT_ID, GITHUB_OAUTH_CLIENT_SECRET) are set and urls on github oauth apps are up-to-date :s

**Comment by jamesward** [comment]
Thanks for giving this a try!  This is due to a mistake in the `app.json` which I just fixed.  But you'll need to rename the Heroku config `APPLICATION_SECRET` to `PLAY_SECRET` - which you can do via the app settings in https://dashboard.heroku.com

Please reopen if you still have issues.
